# SPDX-FileCopyrightText: 2025 Sébastien Helleu <flashcode@flashtux.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1

[[annotations]]
path = [
    "examples/*.json",
    "screenshots/*.png",
    "tasksched/data/html/basic.html",
    "tests/*.json",
    "tests/*.yaml",
]
precedence = "override"
SPDX-FileCopyrightText = "2020-2025 Sébastien Helleu <flashcode@flashtux.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
